# Generated by Django 5.1 on 2024-08-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="img_url",
            field=models.CharField(
                default="https://example.com/default-image.jpg",
                help_text="image url",
                max_length=1000,
                null=True,
                verbose_name="url",
            ),
        ),
    ]
