# Generated by Django 5.1 on 2024-08-13 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_bookinstance_borrow_alter_book_img_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "Set book as returned"),),
            },
        ),
    ]
